name: Claude Headless Review
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install Claude Code
        run: npm install -g @anthropic-ai/claude-code
      - name: Run headless review (read-only)
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        run: |
          set -e
          claude -p "Read the diff and emit a JSON with {style_issues:[], risks:[], summary:''}. No code changes." --output-format json | tee review.json
      - name: Upload JSON artifact
        uses: actions/upload-artifact@v4
        with:
          name: claude-review
          path: review.json
